---
- name: "Users: Add Users"
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    password_lock: "{{ item.password_lock }}"
    shell: "{{ item.shell }}"
    state: present
  when: item.enabled == true
  loop: "{{ users }}"

- name: "Users: Create .ssh if does not exist"
  become: "yes"
  become_user: "{{ item.name }}"
  file:
    path: "~/.ssh"
    state: "directory"
    mode: "0700"
  when: item.enabled == true
  loop: "{{ users }}"

- name: "Users: Remove Users"
  user:
    name: "{{ item.name }}"
    state: absent
  when: item.enabled == false
  loop: "{{ users }}"
