---
- name: "Users: Add Users"
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    password_lock: "{{ item.password_lock }}"
    shell: "{{ item.shell }}"
    state: present
  when: item.enabled == true
  loop: "{{ users }}"

- name: "Users: Remove Users"
  user:
    name: "{{ item.name }}"
    state: absent
  when: item.enabled == false
  loop: "{{ users }}"